### PR TITLE
Custom headers support

### PR DESCRIPTION
**Pull request by garubi**
Added the possibility to add and send custom Headers.
If there are custom Headers, the plugin switch to sending with `SendRawEmail` call, as required by the underliyng `SimpleEmailService PHP class` 

Also, removed some lines referring to `$headers` variable, but not used anywhere

### CODE REVIEW

**Comment by garubi** [comment]
After some time of testing in the wild, I rewrote the whole Headers management (pretty much derived from the origina wp_mail() function).
Now this sholud be quite robust in every situation.

**Comment by bashaus** [comment]
Hey there @garubi !

Thanks for your contribution. I've made some adjustments to this project to modernise it (mainly to match the WordPress coding standards).

Could you please rebase your working version and I will review?

**Comment by bashaus** [comment]
Hey there @garubi ,

I made the amends myself (ended up having some spare time on my hands) and uploaded to the following branch: https://github.com/bashaus/wp-mail-ses/tree/custom-headers-support.

Can you please test this and confirm that you are happy. Also, could you provide me with your WordPress username so that I can add you as a contributor to the readme.

If you'd like to make the changes yourself, go ahead.

**Comment by bashaus** [comment]
I've pulled in the code based on the new template, available in version 0.0.4

It would be great if you could check it out and make sure it's working for you.

**Comment by garubi** [comment]
Hallo,
Great! I'll check it as soon as possible.

I'm now on holidays and have no way to test it until January the 8th.

My WordPress username is 'garubi'.

Stefano

Il 03 Gen 2018 22:07, "Bashkim Isai" <notifications@github.com> ha scritto:

**Pull request closed without merging**
